--[[
	Turns the statistics LootZ saved in your WTF folder into a shareable file,
	and merges any number of them together.

	Usage:
		lua5.1 Tools/MergeStats.lua Database/Shared/SharedStats.lua <input> [<input> ...]

	Each <input> is either
	  - a SavedVariables file:  WTF/Account/<ACCOUNT>/SavedVariables/LootZ.lua
	  - a shared file this tool produced earlier

	Inputs are added together: looting counts and drop counts are summed, and
	the smallest and largest stack sizes are kept. Running it again with the
	same inputs plus a new one is always safe.

	The output is loaded by the addon at startup (it is listed in LootZ.toc) and
	merged into the Stats view, so nobody has to overwrite their own numbers.
]]

local outputPath = arg[1]
local inputPaths = {}
for i = 2, #arg do
	table.insert(inputPaths, arg[i])
end

if (outputPath == nil or #inputPaths == 0) then
	io.stderr:write("usage: lua5.1 Tools/MergeStats.lua <output.lua> <input.lua> [<input.lua> ...]\n")
	os.exit(2)
end

--Reading ---------------------------------------------------------------------

--SavedVariables files are plain Lua assignments, so they can simply be run in
--an empty environment
local function LoadDataFile(path)
	local chunk, err = loadfile(path)
	if (chunk == nil) then
		io.stderr:write("cannot read " .. path .. ": " .. tostring(err) .. "\n")
		os.exit(1)
	end

	--Shared files address globals through _G, saved variables do not
	local env = {}
	env._G = env
	setfenv(chunk, env)

	local ok, runErr = pcall(chunk)
	if (not ok) then
		io.stderr:write("cannot parse " .. path .. ": " .. tostring(runErr) .. "\n")
		os.exit(1)
	end

	--A saved variables file, or a shared file produced by this tool
	local data = env.LediiData_LootZ or env.LEDII_LZ_SHARED
	if (data == nil or data.units == nil) then
		io.stderr:write("no LootZ statistics found in " .. path .. "\n")
		os.exit(1)
	end

	return data.units
end

--Merging ---------------------------------------------------------------------

local function MergeSlot(target, slot)
	if (slot == nil) then return target end
	if (target == nil) then
		return {
			name = slot.name,
			minAmount = slot.minAmount,
			maxAmount = slot.maxAmount,
			totalAmount = slot.totalAmount,
			totalCount = slot.totalCount,
		}
	end

	target.name = target.name or slot.name
	target.minAmount = math.min(target.minAmount, slot.minAmount)
	target.maxAmount = math.max(target.maxAmount, slot.maxAmount)
	target.totalAmount = target.totalAmount + slot.totalAmount
	target.totalCount = target.totalCount + slot.totalCount

	return target
end

local function MergeUnits(target, units)
	for unitId, unit in pairs(units) do
		unitId = tonumber(unitId) or unitId

		local entry = target[unitId]
		if (entry == nil) then
			entry = { name = unit.name, lootingCount = 0, items = {} }
			target[unitId] = entry
		end

		entry.name = entry.name or unit.name
		entry.lootingCount = entry.lootingCount + (unit.lootingCount or 0)
		entry.money = MergeSlot(entry.money, unit.money)

		for itemId, slot in pairs(unit.items or {}) do
			itemId = tonumber(itemId) or itemId
			entry.items[itemId] = MergeSlot(entry.items[itemId], slot)
		end
	end
end

--Writing ---------------------------------------------------------------------

local function Quote(text)
	return string.format("%q", tostring(text))
end

local function SortedKeys(t)
	local keys = {}
	for key in pairs(t) do table.insert(keys, key) end
	table.sort(keys, function(a, b)
		if (type(a) == type(b)) then return a < b end
		return tostring(a) < tostring(b)
	end)
	return keys
end

local function SlotString(slot)
	return string.format(
		"{ name = %s, minAmount = %d, maxAmount = %d, totalAmount = %d, totalCount = %d }",
		Quote(slot.name), slot.minAmount, slot.maxAmount, slot.totalAmount, slot.totalCount
	)
end

local function Write(path, units)
	local out = assert(io.open(path, "w"))

	out:write("--print(\"Loaded <Database/Shared/SharedStats.lua>\")\n")
	out:write("--[[\n")
	out:write("\tShared loot statistics, generated by Tools/MergeStats.lua.\n")
	out:write("\tDo not edit by hand - re-run the tool with the extra data instead.\n")
	out:write("]]\n\n")
	out:write("_G.LEDII_LZ_SHARED = _G.LEDII_LZ_SHARED or {}\n")
	out:write("_G.LEDII_LZ_SHARED.units = _G.LEDII_LZ_SHARED.units or {}\n")
	out:write("local units = _G.LEDII_LZ_SHARED.units\n\n")

	local unitCount, itemCount, lootingCount = 0, 0, 0

	for _, unitId in ipairs(SortedKeys(units)) do
		local unit = units[unitId]
		unitCount = unitCount + 1
		lootingCount = lootingCount + unit.lootingCount

		out:write(string.format("units[%s] = {\n", tostring(unitId)))
		out:write(string.format("\tname = %s,\n", Quote(unit.name)))
		out:write(string.format("\tlootingCount = %d,\n", unit.lootingCount))
		if (unit.money ~= nil) then
			out:write(string.format("\tmoney = %s,\n", SlotString(unit.money)))
		end
		out:write("\titems = {\n")
		for _, itemId in ipairs(SortedKeys(unit.items)) do
			itemCount = itemCount + 1
			out:write(string.format("\t\t[%s] = %s,\n", tostring(itemId), SlotString(unit.items[itemId])))
		end
		out:write("\t},\n")
		out:write("}\n")
	end

	out:close()

	return unitCount, itemCount, lootingCount
end

--Run -------------------------------------------------------------------------

local merged = {}
for i = 1, #inputPaths do
	local units = LoadDataFile(inputPaths[i])
	MergeUnits(merged, units)
	print("read  " .. inputPaths[i])
end

local unitCount, itemCount, lootingCount = Write(outputPath, merged)
print(string.format("wrote %s: %d creatures, %d item entries, %d lootings",
	outputPath, unitCount, itemCount, lootingCount))
